# Generated by Django 5.0.7 on 2024-08-04 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownLoadCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=228, verbose_name='名称')),
                ('format', models.CharField(max_length=228, verbose_name='格式')),
                ('data_number', models.IntegerField(blank=True, null=True, verbose_name='数据条数')),
                ('data_size', models.CharField(blank=True, max_length=228, null=True, verbose_name='文件大小')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, '处理中'), (2, '可下载'), (3, '失败')], default=1, null=True)),
                ('download_link', models.TextField(blank=True, null=True, verbose_name='下载链接')),
                ('task_id', models.CharField(max_length=228, null=True, verbose_name='回调唯一标识')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '下载中心',
                'verbose_name_plural': '下载中心',
            },
        ),
    ]
