# Generated by Django 5.0.7 on 2024-08-04 15:21

import django.db.models.deletion
import django.utils.timezone
import log.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='执行时间')),
                ('action', models.CharField(choices=[('A', '添加了'), ('E', '编辑了'), ('D', '删除了')], max_length=1, verbose_name='动作')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.CharField(max_length=255, null=True, verbose_name='object字符串形式')),
                ('change_message', models.TextField(verbose_name='改变信息')),
                ('client_ip', models.GenericIPAddressField(null=True, verbose_name='客户端IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='contenttypes.contenttype', verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '行为日志',
                'verbose_name_plural': '行为日志',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', log.models.ActionLogManager()),
            ],
        ),
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='执行时间')),
                ('action', models.CharField(choices=[('V', '浏览'), ('D', '导出')], max_length=2, verbose_name='动作')),
                ('page_desc', models.CharField(max_length=255, null=True, verbose_name='页面描述')),
                ('page_url', models.URLField(null=True, verbose_name='页面URL')),
                ('client_ip', models.GenericIPAddressField(null=True, verbose_name='客户端IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client_type', models.CharField(default='PC', max_length=255, verbose_name='客户端类型')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
            ],
            options={
                'verbose_name': '浏览日志',
                'verbose_name_plural': '浏览日志',
                'ordering': ('-created_at',),
                'permissions': (('view_viewlog', '查看浏览日志'),),
                'default_permissions': (),
            },
            managers=[
                ('objects', log.models.ViewLogManager()),
            ],
        ),
    ]
