# Generated by Django 5.0.7 on 2024-10-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_router_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'PC端'), (1, '移动端')], default=0, verbose_name='所属系统'),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
