# Generated by Django 5.0.7 on 2024-10-29 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_type_role_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_comment='邮箱地址', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_page',
            field=models.ForeignKey(blank=True, db_comment='首页', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.router'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, db_comment='手机号', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, db_comment='姓名', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_code',
            field=models.CharField(blank=True, db_comment='工号', max_length=128, null=True),
        ),
    ]
