# Generated by Django 5.0.7 on 2025-01-07 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_at_user_updated_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False, verbose_name='选中')),
                ('partially_selected', models.BooleanField(default=False, verbose_name='半选')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'org')},
            },
        ),
    ]
