# Generated by Django 5.0.7 on 2025-01-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_orgs_userorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orgs',
            field=models.ManyToManyField(related_name='org_users', through='users.UserOrg', to='users.org', verbose_name='组织'),
        ),
    ]
