# Generated by Django 5.0.7 on 2025-01-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userorg_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorg',
            old_name='partially_selected',
            new_name='half_selected',
        ),
    ]
