# Generated by Django 5.0.7 on 2025-01-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_partially_selected_userorg_half_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorg',
            old_name='parent',
            new_name='parent_id',
        ),
        migrations.AddField(
            model_name='userorg',
            name='org_parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
