# Generated by Django 5.0.7 on 2025-01-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_parent_userorg_parent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorg',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
