# Generated by Django 5.0.7 on 2025-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_parent_id_userorg_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='keyword',
            field=models.CharField(blank=True, max_length=228, null=True, verbose_name='角色关键字'),
        ),
    ]
